Sitegeist:
  ArtClasses:
    GoogleCloudVisionInterpreter:
      # The absolute path to the JSON credentials file. See https://github.com/googleapis/google-cloud-php/blob/main/AUTHENTICATION.md
      credentialsFilePath: ''
